spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: cloud
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
mqtt:
  serverUrls: tcp://localhost:1883
  username: admin
  password: admin
  clientId: openstack
  timeout: 1000
  keepalive: 20
server:
  port: 8888