spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: cloud
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
mqtt:
  serverUrls: tcp://47.93.225.95:1883
  username: admin
  password: admin
  clientId: cloud
  timeout: 1000
  keepalive: 20
server:
  port: 8333
#export:
#  name: cloud
#  ip: 127.0.0.1
#  port: 1883
#  publisher: admin
#  user: user
#  password: user
#  topic: edgex